# This workflow will run a suite of tests using the PySys system test framework

name: PySys tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      
      matrix:
        include:
          - test-run-id: ubuntu
            os: ubuntu-latest
            
          - test-run-id: macos
            os: macos-latest
            
          - test-run-id: win
            os: windows-latest
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Install the desired version of Python and PySys
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        id: deps
        run: |
          python -m pip install --upgrade pip
          pip install pysys==1.6.0

          # Use older version of coverage as 5.0 requires an SQLite version that doesn't work on this macos image currently
          pip install coverage==4.5.4
          
      - name: Test with PySys
        working-directory: test
        shell: bash
        id: pysys
        run: |
          python -m pysys run -XcodeCoverage -vdebug --outdir=${{matrix.test-run-id}}
        
      # If any tests fail, PySys will return an error code, so we need "if: always()" so the following steps will run

      - name: Temp Upload code coverage (Python)
        uses: codecov/codecov-action@v1
        if: always()
        with:
          file: test/__coverage_python.${{matrix.test-run-id}}/.coverage

      - name: Upload code coverage (Python)
        uses: codecov/codecov-action@v1
        if: always() && steps.pysys.outputs.artifact_PythonCoverageDir
        with:
          file: test/__coverage_python.${{matrix.test-run-id}}/.coverage
      
      - name: Upload performance CSV artifacts
        uses: actions/upload-artifact@v2
        # Only do this if some performance results were generated
        if: always() && steps.pysys.outputs.artifact_CSVPerformanceReport

        with:
          name: pysys_performance_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_CSVPerformanceReport }}

      - name: Upload test failure archives
        uses: actions/upload-artifact@v2
        if: always() && steps.pysys.outputs.artifact_TestOutputArchiveDir

        with:
          name: pysys_output_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_TestOutputArchiveDir }}
